import { Dimensions, StyleSheet } from 'react-native';

import COLORS from '../constants/colors';

const { width } = Dimensions.get('window');

export const HOME_SCREEN_WIDTH = width;

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: COLORS.background },
  container: { flex: 1 },
  headerWrapper: { paddingHorizontal: 24, paddingTop: 20 },
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: COLORS.white,
    borderRadius: 16,
    height: 48,
    marginTop: 20,
    marginBottom: 10,
    padding: 4,
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
    position: 'relative',
  },
  tabIndicator: {
    position: 'absolute',
    top: 4,
    left: 0,
    width: (width - 48 - 8) / 2,
    height: 40,
    backgroundColor: COLORS.primary + '10',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.primary + '30',
  },
  tabButton: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
  },
  tabText: { fontSize: 14, fontWeight: '700', color: COLORS.textSecondary },
  tabTextActive: { color: COLORS.primary },
  listWrapper: { flex: 1 },
  flatListContent: { paddingHorizontal: 24, paddingTop: 10, paddingBottom: 120 },
  emptyContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', marginTop: 100 },
  emptyTitle: { fontSize: 20, fontWeight: '800', color: COLORS.textPrimary, marginTop: 16 },
  fab: {
    position: 'absolute',
    bottom: 30,
    right: 30,
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 8,
    zIndex: 100,
  },
  fabActive: { backgroundColor: COLORS.secondary },
  fabSelection: { backgroundColor: COLORS.textSecondary },
  fabHidden: { opacity: 0, transform: [{ scale: 0 }] },
  modalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    padding: 24,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  modalContent: {
    width: '100%',
    backgroundColor: COLORS.white,
    borderRadius: 32,
    padding: 30,
    alignItems: 'center',
    elevation: 25,
  },
  lockIconCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: COLORS.primary + '10',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: { fontSize: 24, fontWeight: '900', color: COLORS.textPrimary, marginBottom: 10 },
  modalSubtitle: {
    fontSize: 14,
    color: COLORS.textSecondary,
    textAlign: 'center',
    marginBottom: 24,
  },
  passwordInput: {
    width: '100%',
    height: 56,
    backgroundColor: COLORS.background,
    borderRadius: 16,
    paddingHorizontal: 20,
    fontSize: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  inputError: { borderColor: COLORS.secondary, borderWidth: 2 },
  errorText: { color: COLORS.secondary, fontSize: 13, fontWeight: '600', marginBottom: 20 },
  unlockButton: {
    width: '100%',
    height: 56,
    backgroundColor: COLORS.primary,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 10,
  },
  unlockButtonText: { color: COLORS.white, fontSize: 16, fontWeight: '800' },
  resetButton: { marginTop: 20 },
  resetButtonText: {
    color: COLORS.secondary,
    fontSize: 14,
    fontWeight: '700',
    textDecorationLine: 'underline',
  },
  selectionBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: COLORS.white,
    paddingBottom: 40,
    paddingTop: 20,
    paddingHorizontal: 24,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    elevation: 20,
    zIndex: 200,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  selectionCount: { fontSize: 18, fontWeight: '800' },
  selectionActions: { flexDirection: 'row', gap: 12 },
  selectionButton: { paddingVertical: 10, paddingHorizontal: 16, borderRadius: 14 },
  deleteSelectedButton: { backgroundColor: COLORS.secondary, flexDirection: 'row', gap: 8 },
  cancelText: { color: COLORS.textSecondary, fontWeight: '700' },
  deleteSelectedText: { color: COLORS.white, fontWeight: '700' },
  trashZone: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 150,
    backgroundColor: COLORS.secondary + '15',
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    borderTopWidth: 2,
    borderColor: COLORS.secondary + '30',
    zIndex: 40,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
  },
  trashIconCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: COLORS.white,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
  },
  trashText: { color: COLORS.secondary, fontSize: 14, fontWeight: '900', letterSpacing: 1.5 },
});
